USE [master]
GO

/****** Object:  Database [RecipeBook]    Script Date: 27.11.2017 1:29:03 ******/
CREATE DATABASE [RecipeBook]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RecipeBook', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\RecipeBook.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RecipeBook_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\RecipeBook_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [RecipeBook] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RecipeBook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RecipeBook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RecipeBook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RecipeBook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RecipeBook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RecipeBook] SET ARITHABORT OFF 
GO

ALTER DATABASE [RecipeBook] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RecipeBook] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RecipeBook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RecipeBook] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RecipeBook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RecipeBook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RecipeBook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RecipeBook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RecipeBook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RecipeBook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RecipeBook] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RecipeBook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RecipeBook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RecipeBook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RecipeBook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RecipeBook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RecipeBook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RecipeBook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RecipeBook] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [RecipeBook] SET  MULTI_USER 
GO

ALTER DATABASE [RecipeBook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RecipeBook] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RecipeBook] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RecipeBook] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [RecipeBook] SET  READ_WRITE 
GO


